### ISSUE TITLE
Unable to work on android

### ISSUE THREAD

**Issue by vjsystematix** [markolazic88/SwipeCardView#10]

**Comment by vjsystematix** [comment]
Is there anything which we missed. It's not swiping at all.

**Comment by markolazic88** [comment]
Could you provide any more info? Did you follow the documentation? Did you try the sample?
As far as I know everything still works as documented.

**Comment by vjsystematix** [comment]
yes we followed the documentation and implemented the same. It works like a charm in iOS but in Android the drag is very hard and it happened when dragged on the right & left bottom corner. we have used the swiping commands for left and right. we are unable to drag from the center of the image.

**Comment by markolazic88** [comment]
If you download the sample app from this repo and try it on your Android device, does it behave the same?
Maybe the pictures you use on Android are too big, so Xamarin/Android is not able to render them fast enough?

**Comment by vjsystematix** [comment]
For big pictures we already used FFMPEGCached image library. Inside the DataTemplate we are using Frame for giving shadow and radius. Can you please advice how can we do it just like a demo

**Comment by markolazic88** [comment]
My advice is to start from the sample project, which works fine, and then gradually start updating the template with your elements and test incrementally. That way you will figure out what is putting too much weight on the rendering.

**Comment by pmahend1** [comment]
If we swipe items too fast sometimes we get black image. 
I tried using FFImage but we are using SkiaSharp ImageSourceHandler and generating ImageSource at runtime. So couldnt use FFImageLoading as it says invalid value for ImageSource.

I also tried making SwipeCommand bound to async method.

@markolazic88 Any suggestions?

**Comment by markolazic88** [comment]
@pmahend1 I missed your comment. I hope you fixed your issue by now. If not, feel free to open a new issue with as much details as possible. Closing this one.
