### ISSUE TITLE
Is it possible to order item vertical like in build ListView?

### ISSUE THREAD

**Issue by SagarPanwala** [markolazic88/SwipeCardView#13]
Is there any way to arrange data in vertical direction ?
so when user swipe left I want to remove that item and next item will shows up and we can scroll like a listview too.

**Comment by markolazic88** [comment]
SwipeCardView iterates through ItemSource collection. If you want a specific order, then you should order ItemSource in the manner that suits your needs. There is no OrderBy/Sort property exposed by SwipeCardView, if that's what you are asking.
