### ISSUE TITLE
Too fast swipe - blank image on Android sometimes

### ISSUE THREAD

**Issue by pmahend1** [markolazic88/SwipeCardView#15]
If we swipe too fast on Android sometimes we get blank image.

- Itemsource is bound to ObservableCollection of Imagesources
SwipedCommand is bound to async method and I am using await in it , also added some Task.Delay(200) in it

- If I fast too fast like 3-4 images within a second I get blank image 

- Please note since ImageSources are generated from SkiaSharp SKImageImageSource I am unable to use FFImageLoading-CachedImage 
it gives error invalid ImageSource

**Comment by markolazic88** [comment]
Hey @pmahend1 , this is an interesting one. Does the image stays blank or it gets rendered at some moment before next swipe?
Could it be that you are blocking the main thread in your Swiped handler which prevents Xamarin.Forms to render the image?
What happens if you comment out your awaits?

**Comment by pmahend1** [comment]
@markolazic88 Image is not completely blank. It gets a background but only main image isnt there ..

```SKSurface.SnapShot()``` and then ```Imagesource = new SKImageImageSource(){Image = SKSurface.SnapShot(), }``` is the code

**Comment by pmahend1** [comment]
@markolazic88 nevermind we found a workaround

**Comment by jefflafay** [comment]
@pmahend1 could you share the work around? I'm having the same issue. The second card is always blank for my app but then the cards appear for the remaining cards.

**Comment by pmahend1** [comment]
@jefflafay  make the command async and use `CanExecute`, while swiping or the current command execution not complete `CanExecute= false`
