### ISSUE TITLE
Problem install NuGet Package

### ISSUE THREAD

**Issue by s-figuccia** [markolazic88/SwipeCardView#16]
Hi,
this is my problem: when I try to install your package in my Xamarin forms project, show this message:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package SwipeCardView 3.0.0 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Package SwipeCardView 3.0.0 supports: monoandroid81 (MonoAndroid,Version=v8.1)	Glancy.iOS

Do you have any solution about this?

**Comment by markolazic88** [comment]
I believe you are trying to install the wrong NuGet package. My package is called [MLToolkit.Forms.SwipeCardView](https://www.nuget.org/packages/MLToolkit.Forms.SwipeCardView/) and is intended to be used in Xamarin.Forms projects. You don't have to install it in platform specific projects.

**Comment by s-figuccia** [comment]
Yes, you are right. Sorry for the inconvenience and thank you ;)
