### ISSUE TITLE
Some more improve explain about library

### ISSUE THREAD

**Issue by KingAndroid** [markolazic88/SwipeCardView#2]
- could you please explain about `xmls` config?
```
xmlns:swipecards="clr-namespace:SwipeCards.Controls;assembly=SwipeCards.Controls"
```

- could you please add some demo?
swipe does not work, some thing is wrong, I think.

**Comment by markolazic88** [comment]
Please check which library you are using before posting the issue. This is not a namespace from my library. 
But anyway, xmlns stands for Xamarin Forms XAML namespace. Please refer to [Xamarin documentation](https://developer.xamarin.com/guides/xamarin-forms/xaml/namespaces/). This is just a standard way of importing namespace into XAML. In my library it would be:

`xmlns:swipeCardView="clr-namespace:MLToolkit.Forms.SwipeCardView;assembly=MLToolkit.Forms.SwipeCardView"`


Full working example can be found on my GitHub repository. It’s an image gallery app called [DailyCat](https://github.com/markolazic88/DailyCat).

For a detailed explanation of design, implementation and usage of this library, check my blog post: [Create Tinder-like UI in Xamarin Forms using SwipeCardView.](https://markolazic.com/swipecardview-tinder-ui-xamarin-forms/)
