### ISSUE TITLE
InvokeSwipe swipe all my cards

### ISSUE THREAD

**Issue by Clement-Jean** [markolazic88/SwipeCardView#9]
I'm currently try to swipe a card programatically so I use InvokeSwipe, but it appears that all my cards are swipped.

Is it a normal behavior ?

Ps: I'm on UWP if it can help

**Comment by Clement-Jean** [comment]
It appears that the swipe right closes everything but the swipe left closes just one

**Comment by markolazic88** [comment]
I just debugged on Android and InvokeSwipe works as expected. You can clone this repo and run Sample project on Android on iOS. Buttons on TinderPage execute InvokeSwipe in Left, Up and Right directions.
That being said, I didn't test on UWP. InvokeSwipe code is pretty straightforward, and I don't see any reason why swipe in one direction would work differently on UWP. Maybe you could run TinderPage on UWP and see what happens?

**Comment by Clement-Jean** [comment]
It seems to work, I don't know what was the problem I had
